xcodeproj './iOS/stitchchat.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket', 'RCTPushNotification', 'RCTSettings', 'RCTLinkingIOS', 'RCTCameraRoll', 'ART', 'RCTActionSheet'], :path => 'node_modules/react-native'
pod 'react-native-image-picker', :path => 'node_modules/react-native-image-picker'
pod 'CodePush', :path => './node_modules/react-native-code-push'
pod 'Fabric'
pod 'Crashlytics'
pod 'Digits'
pod 'TwitterCore'
pod 'libPhoneNumber-iOS'
pod 'AFNetworking', '~> 3.0.4'
pod 'CTAssetsPickerController',  '~> 3.3.1'
